module.exports = {
	roots: ["<rootDir>/src"],
	collectCoverageFrom: ["src/**/*.{js,jsx,ts,tsx}", "!src/**/*.d.ts"],
	setupFiles: ["react-app-polyfill/jsdom"],
	setupFilesAfterEnv: [],
	testMatch: ["<rootDir>/src/**/__tests__/**/*.{js,jsx,ts,tsx}", "<rootDir>/src/**/*.{spec,test}.{js,jsx,ts,tsx}"],
	testEnvironment: "jest-environment-jsdom-fourteen",
	transform: {
		"^.+\\.tsx?$": "<rootDir>/node_modules/ts-jest",
		"^.+\\.(js|jsx)$": "<rootDir>/node_modules/babel-jest",
		"^.+\\.(css|scss|sass)$": "<rootDir>/config/jest/cssTransform.js",
		"^(?!.*\\.(js|jsx|ts|tsx|css|json)$)": "<rootDir>/config/jest/fileTransform.js",
	},
	transformIgnorePatterns: ["[/\\\\]node_modules[/\\\\].+\\.(js|jsx|ts|tsx)$", "^.+\\.module\\.(css|sass|scss)$"],
	modulePaths: [],
	moduleNameMapper: {
		"^react-native$": "react-native-web",
		"\\.(css|less|scss|sass)$": "identity-obj-proxy",
		"^src(.*)$": "<rootDir>/src$1",
		"^components(.*)$": "<rootDir>/src/components$1",
		"^hooks(.*)$": "<rootDir>/src/hooks$1",
		"^helpers(.*)$": "<rootDir>/src/helpers$1",
		"^screens(.*)$": "<rootDir>/src/screens$1",
		"^styles(.*)$": "<rootDir>/src/styles$1",
		"^state(.*)$": "<rootDir>/src/state$1",
	},
	moduleFileExtensions: ["web.js", "js", "web.ts", "ts", "web.tsx", "tsx", "json", "web.jsx", "jsx", "node"],
	watchPlugins: ["jest-watch-typeahead/filename", "jest-watch-typeahead/testname"],
};
