FROM node:11.2.0 as builder

WORKDIR /
COPY package*.json ./
RUN npm install
COPY . .
RUN npm run build

FROM nginx
WORKDIR /build/
COPY --from=builder /build/ .
COPY scripts/nginx.production.conf /etc/nginx/conf.d/default.conf
