node {
  checkout(scm)

  stage('deploy web app to staging') {
    if (BRANCH_NAME == 'develop') {
      echo 'deploying to staging...'
      updateGitlabCommitStatus(name: '2 - deploy', state: 'running')
      sh '''
        cd ./scripts &&
        make build-staging
        make stop-staging
        make run-staging
      '''
      echo 'deploying to staging...done!'
    }
  }

  stage('deploy web app to production') {
    if (BRANCH_NAME == 'master') {
      echo 'deploying to production...'
      updateGitlabCommitStatus(name: '2 - deploy', state: 'running')
      sh '''
        cd ./scripts &&
        make build-production
        make stop-production
        make run-production
      '''
      echo 'deploying to production...done!'
    }
  }
}
